name: env_pywindow
dependencies:
  - python=3.8
  - pip=22.3.1
  - pip:
      - numpy
      - matplotlib
      - scipy
      - pyqt5
      - pyqt5-tools
      - qt-material
      - gradio
      - langchain